baseURL = "https://asahilinux.org/"
defaultContentLanguage = 'en'
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1
  [languages.fr]
    contentDir = 'content/fr'
    languageCode = 'fr-FR'
    languageName = 'Français'
    weight = 2
title = "Asahi Linux"

pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe = true

[minify.tdewolff.html]
keepWhitespace = true

[permalinks]
blog = "/:year/:month/:slug/"

[outputs]
page = ["HTML"]
home = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]

[privacy.twitter]
enableDNT = true
